# Use docker compose to launch app locally
version: "3.8"

services:
  # Redis Cache service
  redis:
    container_name: upsale-cache-db
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    volumes:
      - upsale_redis_storage:/data

  # # MongoDB service
  # mongodb:
  #   container_name: upsale-db
  #   image: mongodb/mongodb-community-server:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - upsale_mongo_storage:/data/db

  # App service
  app:
    build: .
    container_name: "upsale-service"
    image: "upsale-service:latest"
    ports:
      - "7860:7860"
    volumes:
      - .:/home/user/app
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      # - MONGO_HOST=mongodb
    develop:
      watch:
        - path: .
          action: sync
          target: /home/user/app
          ignore:
            - .git
            - env
            - .env
            # - terraform
            # - kubernetes
    depends_on:
      redis:
        condition: service_started
      mongodb:
        condition: service_started

volumes:
  upsale_redis_storage:
    driver: local
  # upsale_mongo_storage:
  #   driver: local