apiVersion: apps/v1
kind: Deployment
metadata:
  name: upsale-deployment
  labels:
    app: upsale

spec:
  replicas: 1
  selector:
    matchLabels:
      app: upsale
    template:
      metadata:
        labels:
          app: upsale
      spec:
        containers:
          - name: upsale-service
            image: upsale/upsale-service:latest
            ports:
              - containerPort: 7860
          - name: redis
            image: redis/redis-stack-server:latest
            ports:
              - containerPort: 6379